apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api 
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
#  strategy:
#    type: Recreate
  template:
    metadata:
      name: flask-api-pod
      labels:
        app: flask-app
    spec:
      containers:
      - image: omartarekabdelall/flask-api:v1
        name: flask-container
        ports:
        - containerPort: 5000
          name: flask-api-port
---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  labels:
    app: flask-app
spec:
 # type: NodePort
  ports:
    - protocol: TCP 
     # nodePort: 30001
      port: 5000
      targetPort: 5000
  selector:
    app: flask-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress-svc
  namespace: flask
spec:
  ingressClassName: nginx
  rules:
     # host: todolist.app.com
      - http:
          paths:
            - path: /             #/api --> http://localhost/api
              pathType: Prefix
              backend:
                  service:
                    name: flask-svc
                    port:
                      number: 5000
                
